"""Copy the trained model and its metadata from the ML pipeline into app/assets/.

Run from the repo root after `python src/export/to_tflite.py` (and optionally quantize.py):

    python app/tool/sync_assets.py                       # head + labels + thresholds
    python app/tool/sync_assets.py --yamnet models/exported/yamnet.tflite

Writes:
    app/assets/labels.txt               SOUND_CLASSES from src/config.py, one per line, in model order
    app/assets/class_thresholds.json    copy of data/metadata/class_thresholds.json
    app/assets/sahara_classifier.tflite sahara_int8.tflite if present, else sahara_fp32.tflite
    app/assets/yamnet.tflite            only with --yamnet (see export_yamnet_tflite.py)

Needs only the standard library (it parses src/config.py instead of importing TensorFlow).
"""
from __future__ import annotations

import argparse
import ast
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ASSETS = REPO_ROOT / "app" / "assets"


def sound_classes(config: Path = REPO_ROOT / "src" / "config.py") -> list[str]:
    tree = ast.parse(config.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "SOUND_CLASSES" for t in node.targets):
            return [ast.literal_eval(e) for e in node.value.elts]
    raise SystemExit(f"SOUND_CLASSES not found in {config}")


def write_labels(target: Path = ASSETS / "labels.txt") -> list[str]:
    classes = sound_classes()
    target.write_text(
        "# Generated by app/tool/sync_assets.py from SOUND_CLASSES in src/config.py. Do not edit.\n"
        + "\n".join(classes)
        + "\n",
        encoding="utf-8",
    )
    return classes


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model", type=Path, help="classifier .tflite (default: newest export)")
    parser.add_argument("--yamnet", type=Path, help="YAMNet .tflite with an embeddings output")
    parser.add_argument("--labels-only", action="store_true", help="only write labels.txt and thresholds")
    args = parser.parse_args()

    ASSETS.mkdir(parents=True, exist_ok=True)
    classes = write_labels()
    print(f"labels.txt: {len(classes)} classes -> {', '.join(classes)}")

    thresholds = REPO_ROOT / "data" / "metadata" / "class_thresholds.json"
    if thresholds.exists():
        shutil.copyfile(thresholds, ASSETS / "class_thresholds.json")
        print(f"class_thresholds.json: copied from {thresholds.relative_to(REPO_ROOT)}")
    if args.labels_only:
        return

    exported = REPO_ROOT / "models" / "exported"
    model = args.model or next(
        (p for p in (exported / "sahara_int8.tflite", exported / "sahara_fp32.tflite") if p.exists()), None
    )
    if model is None:
        print("No exported classifier found. Run src/export/to_tflite.py first; the app will say the model is missing.")
    else:
        shutil.copyfile(model, ASSETS / "sahara_classifier.tflite")
        print(f"sahara_classifier.tflite: {model} ({model.stat().st_size / 1024:.1f} KiB)")

    if args.yamnet:
        shutil.copyfile(args.yamnet, ASSETS / "yamnet.tflite")
        print(f"yamnet.tflite: {args.yamnet} ({args.yamnet.stat().st_size / 1024:.1f} KiB)")
    elif not (ASSETS / "yamnet.tflite").exists():
        print("yamnet.tflite missing: run app/tool/export_yamnet_tflite.py, then pass --yamnet.")


if __name__ == "__main__":
    main()
